version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  java:
    image: openjdk:latest

  elasticsearch:
    image: elasticsearch:latest

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    ports:
      - "3000:3000"
    links:
      - db
      - java
      - elasticsearch
    volumes:
      - .:/social-recipes_henrique
