version: '2'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails server --port 80 --binding 0.0.0.0
    links:
      - db
    volumes:
      - .:/social-recipes_henrique